# Site settings
title: LLM Coup
description: How well can LLMs perform at games of strategic deception and multi-level planning?
# baseurl: "/llm-coup" # Important: must match your repository name
# url: "https://khoj-ai.github.io" # Your organization's GitHub Pages URL

# Route to custom domain
baseurl: ""
url: "https://coup.khoj.dev"

# Social media links (Minima will automatically add icons to header)
minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/khoj_ai" }
    - { platform: github, user_url: "https://github.com/khoj-ai/llm-coup" }
  social_links:
    - platform: Twitter
      icon: x-twitter
      url: "https://twitter.com/khoj_ai"
    - platform: GitHub
      icon: github
      url: "https://github.com/khoj-ai/"

# Theme
theme: minima

author:
  name: "Saba Imran"
  url: "https://twitter.com/sabaimran_go"

# Build settings
markdown: kramdown
highlighter: rouge

# Title generation from headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

# Navigation
header_pages:
  - index.md
  - code.md

# GitHub integration
github:
  repository_url: https://github.com/khoj-ai/llm-coup
  
# Optional: Add organization info
organization: khoj-ai

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

search: true