# Site settings
title: LLM Coup
description: How well can LLMs perform at games of strategic deception and multi-level planning?
baseurl: "/llm-coup" # Important: must match your repository name
url: "https://khoj-ai.github.io" # Your organization's GitHub Pages URL

# Theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Title generation from headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

# Navigation
header_pages:
  - code.md

# GitHub integration
github:
  repository_url: https://github.com/khoj-ai/llm-coup
  
# Optional: Add organization info
organization: khoj-ai

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

search: true